Traceback (most recent call last):
  File "C:\Users\USUARIO\miniconda3\envs\ml_venv\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\USUARIO\miniconda3\envs\ml_venv\lib\site-packages\nbclient\client.py", line 1117, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\USUARIO\miniconda3\envs\ml_venv\lib\site-packages\nbclient\util.py", line 78, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\USUARIO\miniconda3\envs\ml_venv\lib\site-packages\nbclient\util.py", line 57, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\USUARIO\miniconda3\envs\ml_venv\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\USUARIO\miniconda3\envs\ml_venv\lib\site-packages\nbclient\client.py", line 558, in async_execute
    await self.async_execute_cell(
  File "C:\Users\USUARIO\miniconda3\envs\ml_venv\lib\site-packages\nbclient\client.py", line 862, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "C:\Users\USUARIO\miniconda3\envs\ml_venv\lib\site-packages\nbclient\client.py", line 765, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from sklearn.neighbors import KNeighborsRegressor
from sklearn.linear_model import Ridge, Lasso
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVR
from sklearn.neural_network import MLPRegressor
from xgboost import XGBRegressor
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.model_selection import GridSearchCV, TimeSeriesSplit
from sklearn.metrics import mean_squared_error, mean_absolute_percentage_error
from sklearn.model_selection import train_test_split
from keras.models import Sequential
from keras.layers import Dense, LSTM, Dropout, GRU
from keras.wrappers.scikit_learn import KerasRegressor
import pickle
import glob
from tensorflow.keras.models import load_model
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
[1;32m~\AppData\Local\Temp/ipykernel_121192/692206779.py[0m in [0;36m<module>[1;34m[0m
[0;32m     12[0m [1;32mfrom[0m [0mkeras[0m[1;33m.[0m[0mmodels[0m [1;32mimport[0m [0mSequential[0m[1;33m[0m[1;33m[0m[0m
[0;32m     13[0m [1;32mfrom[0m [0mkeras[0m[1;33m.[0m[0mlayers[0m [1;32mimport[0m [0mDense[0m[1;33m,[0m [0mLSTM[0m[1;33m,[0m [0mDropout[0m[1;33m,[0m [0mGRU[0m[1;33m[0m[1;33m[0m[0m
[1;32m---> 14[1;33m [1;32mfrom[0m [0mkeras[0m[1;33m.[0m[0mwrappers[0m[1;33m.[0m[0mscikit_learn[0m [1;32mimport[0m [0mKerasRegressor[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m     15[0m [1;32mimport[0m [0mpickle[0m[1;33m[0m[1;33m[0m[0m
[0;32m     16[0m [1;32mimport[0m [0mglob[0m[1;33m[0m[1;33m[0m[0m

[1;31mModuleNotFoundError[0m: No module named 'keras.wrappers'
ModuleNotFoundError: No module named 'keras.wrappers'

